image: alpine/3.20
packages:
  - npm
secrets:
  - e2e843cf-6f7e-4b74-989f-819a97ca70b8
sources:
  - git+ssh://git@git.sr.ht/~mattmundell/build
environment:
  PKG: build
tasks:
  - mirror: |
      cd $PKG && ./bin/mirror
